export const CRAWL_START = 'CRAWL_START'

export const FETCH_BOARD_LIST = 'FETCH_BOARD_LIST'
export const FETCH_BOARD = 'FETCH_BOARD'

export const FETCH_FUNDING_LIST = 'FETCH_FUNDING_LIST'
export const FETCH_FUNDING = 'FETCH_FUNDING'

export const FETCH_MEMBER_LIST = 'FETCH_MEMBER_LIST'
export const FETCH_MEMBER = 'FETCH_MEMBER'